services:
  slim_container:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # Mount the workspace directory
      - ../:/workspace:cached
      # Mount the local SSH directory
      - ~/.ssh:/root/.ssh
      # Mount the local Databricks configuration file
      - ~/.databrickscfg:/root/.databrickscfg:ro
