name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cd:
    name: Build and Push ${{ matrix.image.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - name: revo-devops-agent
            dockerfile: ./src/revo-devops-agent/Dockerfile
            tag: "24.04"
            context: ./src/revo-devops-agent

          - name: revo-devcontainer-databricksruntime
            dockerfile: ./src/revo-devcontainer-databricksruntime/Dockerfile
            tag: "15.4-LTS"
            context: ./src/revo-devcontainer-databricksruntime

          - name: revo-devcontainer-slim
            dockerfile: ./src/revo-devcontainer-slim/Dockerfile
            tag: "3.11.11"
            context: ./src/revo-devcontainer-slim

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:${{ matrix.image.tag }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:latest
            
      - name: Deploy summary
        run: |
          echo "🚀 Successfully deployed:"
          echo "  📦 ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:${{ matrix.image.tag }}"
          echo "  📦 ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:latest"