name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cd:
    name: Build and Push ${{ matrix.image.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - name: revo-devcontainer-databricks
            dockerfile: ./src/revo-devcontainer-databricks/Dockerfile
            tag: 24.04
            additional_tags: latest
            context: ./src/revo-devcontainer-databricks
            base_image_version: 24.04
            platforms: linux/amd64,linux/arm64

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          platforms: ${{ matrix.image.platforms }}
          push: true
          build-args: |
            BASE_IMAGE_VERSION=${{ matrix.image.base_image_version }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:${{ matrix.image.tag }}
            ${{ matrix.image.additional_tags && format('ghcr.io/{0}/{1}:{2}', github.repository_owner, matrix.image.name, matrix.image.additional_tags) || '' }}
          cache-from: type=gha,scope=${{ matrix.image.name }}-${{ matrix.image.tag }}
          cache-to: type=gha,mode=max,scope=${{ matrix.image.name }}-${{ matrix.image.tag }}
            
      - name: Deploy summary
        run: |
          echo "🚀 Successfully deployed:"
          echo "  📦 ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:${{ matrix.image.tag }}"
          if [[ -n "${{ matrix.image.additional_tags }}" ]]; then
            echo "  📦 ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:${{ matrix.image.additional_tags }}"
          fi
          echo "  🏗️  Built for platforms: ${{ matrix.image.platforms }}"
          echo "  🐍 Base Image Version: ${{ matrix.image.base_image_version }}"
  
  # Tests run post-build to ensure container is built correctly
  # since docker buildx only supports building and pushing images simultaneously
  functionality-tests:
    name: Test Container Functionality
    runs-on: ubuntu-latest
    needs: cd
    if: ${{ success() }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: revo-devcontainer-databricks
            tag: latest
            python_version: 3.11.11  # only needed for CI testing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull ${{ matrix.image.name }} from registry
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:${{ matrix.image.tag }}

      - name: Test Databricks Container
        run: |
          .github/scripts/test-databricks-container.sh ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }} ${{ matrix.image.tag }} ${{ matrix.image.python_version }}
